name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-06"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDg5Yjg1MDgtMDYxYi00NzE4LTliZmYtZmYxMDA5YTFhMTkxIiwidGVuYW50X2lkIjoiNTk5MDhjN2E2NGZhNTgxYjJlMzk4NTljMzhkZjE2YmZiMDVkN2Q2MjQzNzY3MGUyMTk3MGUzZTQ4YTU2NWNjNCIsImludGVybmFsX3NlY3JldCI6ImJjZTE1YzczLTk4NzUtNDIzZC1hYWE3LTBmMzMyMDM4MDcwMyJ9.YEwt4qlUTRH3f5oqkbax37knD1o9FRJdibUegTPnc_4"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1